name: Build `masl-dev` Docker Image
on:
  workflow_dispatch:

jobs:
  masl-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=true
          images: levistarrett/masl-dev
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/masl-dev"
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
